sudo: required
services:
  - docker

before_install:
  - docker build -t hlonza/docker-react -f Dockerfile.dev .


script:
  - docker run  hlonza/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-452929811925Info"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEYS
  secrete_access_key:
    secure:  "$AWS_SECRET_KEY"
